language: python
python:
- '2.7'
before_install:
- git log --no-merges -n 1 > changes.md
install:
- pip install -r requirements.txt
script:
- make clean
- make release
deploy:
  provider: releases
  api_key:
    secure: fMxKHp4GsrjfloTa/a5Iu7wqz+15qrkDdnf7z9Uh04VQfkv7YLmw0yiEJVKx3EH3bXosFTydx7Xg/ZHTsRtqDntC4zdzcNtKt7CNPMuhZG3MyxCzi90WOlbfNSVW2OjUenFzKftjSRc6HZaOSOV+1e5EN1BIuBx1z0OIton/5hOVijkFHXLjYdRbEyUht9Dc9NUhgCvlKjwB1dhfsbI1oP3Zj+x7thMeVRbjERMilyX56YqHsDcRD+FuEnSRBZX4xxfEMMQWeZ8qd98zbeLMv0jW9ID6xtWUNgDkfD7zNIrhVdyk1rSOObjjyjnYa99jSqHnP4bNnpVVwXxYA/lFWaN4IYQdv9673SvWW1Op+tojpWuWvyQVL+rt8D+9GcOOKHZ+LbzA2EEMdTg8DPRGkf1TX+rf7Bfl5Jgkeh5pT0dy0Udq8ewTblgg8RPTJdxch8TL91jAXVu1GvEhN0H9zLhCt22wCuOwoygsG67vuD0G/v7Cc7//CtrAkk2mSC5eoLpZ5xP/LBJqIrdp8EoopcneC0aS1T72Y16B2cKppw3rywtTOnOHnR+MKpvSfOJrofImYo/HSq0+DWTcPMnEpdKVI+bmu4lQxaPpSSt+xV16zgCW8zct8fZOnLwn5o50RqKqr+Doag4EXPq+01TGgKiDF4avnh5pUiO1yo3H4YY=
  file_glob: true
  file: RSSDateTime*.zip
  on:
    repo: KSP-RO/RSSTimeFormatter
    tags: true
    all_branches: true
